version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    hostname: server.docker
    environment:
      - TZ=Europe/Helsinki
    volumes:
      - ./servervol:/serverdata

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    hostname: client.docker
    environment:
      - TZ=Europe/Helsinki
    volumes:
      - ./clientvol:/clientdata
    ports:
      - 80:80

volumes:
  servervol:
  clientvol:
